const STUDENT_INFO = [
  {
    id: 1,
    name: "Bruno DaSilva",
    title: "Full-Stack Developer",
    imgUrl:
      "https://res.cloudinary.com/duprwuo4j/image/upload/v1578119088/imgs_starwars/imgs/Bruno-Profile_jsk4wb.png",
    country: "United States",
    state: "Texas",
    city: "Dallas",
    latitude: 32.779167,
    longitude: -96.808891,
    aboutDescription: `"Hello World". I am a Front-End Developer with Full-Stack exposure and 6 years of experience in various IT-related fields, from client support to data analytics and server-side automation. I am passionate about coding and teaching, but especially, I love to be part of a student's development path; there is nothing like seeing and guiding them from their first "Hello world" app to a fully interactive and functional real-world application. These days you can find me busy developing automation solutions for server-side applications. In my spare time, I love to enjoy my beautiful family, play some video games or board games with them, and play some soccer on the weekends.`,
    linkedin: "https://www.linkedin.com/in/bruno-dasilva/",
    portfolio: "https://www.bruno-dasilva.com/",
    github: "https://github.com/Brunno-DaSilva",
  },
  {
    id: 2,
    name: "Elizabeth DaSilva",
    title: "Designer & Developer",
    imgUrl:
      "https://res.cloudinary.com/duprwuo4j/image/upload/v1599168095/imgs_starwars/imgs/0_lc24ad.jpg",
    country: "United States",
    state: "Texas",
    city: "Frisco",
    latitude: 33.155373,
    longitude: -96.818733,
    aboutDescription: `Dallas-based designer with experience in graphic design, UX design, and front-end development. I love great design and learning new ways to delight viewers and communicate the values and messages of my clients. When I’m not tinkering on a design or code, you can find me reading a book, cooking, traveling with my family, or running after my two kids.`,
    linkedin: "https://www.linkedin.com/in/lizdasilva/detail/photo/",
    portfolio: "https://mcsilva-design.bruno-dasilva.com/",
    github: "https://github.com/Brunno-DaSilva",
  },
  {
    id: 3,
    name: "Elizabeth DaSilva",
    title: "Designer & Developer",
    imgUrl:
      "https://res.cloudinary.com/duprwuo4j/image/upload/v1599168095/imgs_starwars/imgs/0_lc24ad.jpg",
    country: "United States",
    state: "Texas",
    city: "Frisco",
    latitude: 33.155373,
    longitude: -96.818733,
    aboutDescription: `Dallas-based designer with experience in graphic design, UX design, and front-end development. I love great design and learning new ways to delight viewers and communicate the values and messages of my clients. When I’m not tinkering on a design or code, you can find me reading a book, cooking, traveling with my family, or running after my two kids.`,
    linkedin: "https://www.linkedin.com/in/lizdasilva/detail/photo/",
    portfolio: "https://mcsilva-design.bruno-dasilva.com/",
    github: "https://github.com/Brunno-DaSilva",
  },
  {
    id: 4,
    name: "Elizabeth DaSilva",
    title: "Designer & Developer",
    imgUrl:
      "https://res.cloudinary.com/duprwuo4j/image/upload/v1599168095/imgs_starwars/imgs/0_lc24ad.jpg",
    country: "United States",
    state: "Texas",
    city: "Frisco",
    latitude: 33.155373,
    longitude: -96.818733,
    aboutDescription: `Dallas-based designer with experience in graphic design, UX design, and front-end development. I love great design and learning new ways to delight viewers and communicate the values and messages of my clients. When I’m not tinkering on a design or code, you can find me reading a book, cooking, traveling with my family, or running after my two kids.`,
    linkedin: "https://www.linkedin.com/in/lizdasilva/detail/photo/",
    portfolio: "https://mcsilva-design.bruno-dasilva.com/",
    github: "https://github.com/Brunno-DaSilva",
  },
  {
    id: 5,
    name: "Elizabeth DaSilva",
    title: "Designer & Developer",
    imgUrl:
      "https://res.cloudinary.com/duprwuo4j/image/upload/v1599168095/imgs_starwars/imgs/0_lc24ad.jpg",
    country: "United States",
    state: "Texas",
    city: "Frisco",
    latitude: 33.155373,
    longitude: -96.818733,
    aboutDescription: `Dallas-based designer with experience in graphic design, UX design, and front-end development. I love great design and learning new ways to delight viewers and communicate the values and messages of my clients. When I’m not tinkering on a design or code, you can find me reading a book, cooking, traveling with my family, or running after my two kids.`,
    linkedin: "https://www.linkedin.com/in/lizdasilva/detail/photo/",
    portfolio: "https://mcsilva-design.bruno-dasilva.com/",
    github: "https://github.com/Brunno-DaSilva",
  },
  {
    id: 6,
    name: "Elizabeth DaSilva",
    title: "Designer & Developer",
    imgUrl:
      "https://res.cloudinary.com/duprwuo4j/image/upload/v1599168095/imgs_starwars/imgs/0_lc24ad.jpg",
    country: "United States",
    state: "Texas",
    city: "Frisco",
    latitude: 33.155373,
    longitude: -96.818733,
    aboutDescription: `Dallas-based designer with experience in graphic design, UX design, and front-end development. I love great design and learning new ways to delight viewers and communicate the values and messages of my clients. When I’m not tinkering on a design or code, you can find me reading a book, cooking, traveling with my family, or running after my two kids.`,
    linkedin: "https://www.linkedin.com/in/lizdasilva/detail/photo/",
    portfolio: "https://mcsilva-design.bruno-dasilva.com/",
    github: "https://github.com/Brunno-DaSilva",
  },

  //Add your information below:
];

export default STUDENT_INFO;
